# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_smtp_password: 123456

development:
  <<: *default
  secret_key_base: de11c1a74269a6b6d5f59bf72f3d3cce6fc2d482829ed3c04a1959b60e056c7c7be1757bc9ee507484997ce7121712fd94eb709a0fa1f56b23a810d641091ac6

test:
  <<: *default
  secret_key_base: 8c6ce92c6f025bf05d7237f33f575b62e5dc45165a5f1dc450a414cbbd869bc880c3a738b131a9efc0bde93daa066356af5b85438714a14ee8794282409149bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_host: <%= ENV["SMTP_HOST"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  secret_smtp_password: <%= ENV["SECRET_SMTP_PASSWORD"] %>
